# tasks file for Ubuntu distribution
---
  - name: Install required packages for KVM 
    apt:
      name: "{{ kvm_packages }}"
      state: present
      update_cache: true
      install_recommends: false
