# docker-engine tasks for Ubuntu
---
  - name: Remove docker deprecated packages
    apt:
      name: "{{ docker_engine.deprecated_packages }}"
      state: absent

  - name: Install docker required packages
    apt:
      name: "{{ docker_engine.required_packages }}"
      state: present
      update_cache: yes

  - name: add Docker’s official GPG key
    apt_key:
      url: "{{ docker_engine.repo_baseurl }}/gpg"
      id: "{{ docker_engine.repo_gpgkey }}"
      state: present

  - name: Add docker official repository
    apt_repository:
      repo: "deb [arch=amd64] {{ docker_engine.repo_baseurl }} {{ansible_distribution_release}} stable"

  - name: Install docker packages
    apt:
      name: "{{ docker_engine.packages }}"
      state: present

